import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Stylish Blue Dress',
    description: 'A beautiful and stylish blue dress perfect for any occasion. Made from high-quality fabric.',
    price: 2999,
    category: 'Dresses',
    brand: 'Chic Boutique',
    tags: ['formal', 'party wear', 'elegant'],
    imageId: 'prod-1',
    rating: 4.5,
    reviewCount: 120,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['prod-1'],
  },
  {
    id: 'prod-2',
    name: 'Elegant High Heels',
    description: 'Elegant high-heeled shoes that add a touch of class to your outfit. Available in various sizes.',
    price: 4500,
    category: 'Shoes',
    brand: 'Stylo Steps',
    tags: ['heels', 'formal', 'footwear'],
    imageId: 'prod-2',
    rating: 4.8,
    reviewCount: 88,
    featured: false,
    sizes: ['6', '7', '8', '9'],
    images: ['prod-2'],
  },
  {
    id: 'prod-3',
    name: 'Modern Leather Handbag',
    description: 'A modern and spacious leather handbag. Perfect for daily use and carrying all your essentials.',
    price: 3200,
    category: 'Accessories',
    brand: 'Urban Tote',
    tags: ['handbag', 'leather', 'daily use'],
    imageId: 'prod-3',
    rating: 4.7,
    reviewCount: 150,
    featured: true,
    images: ['prod-3'],
  },
  {
    id: 'prod-4',
    name: 'Floral Summer Skirt',
    description: 'A chic floral print summer skirt. Lightweight and comfortable for warm weather.',
    price: 1800,
    category: 'Skirts',
    brand: 'Summer Blooms',
    tags: ['skirt', 'floral', 'summer'],
    imageId: 'prod-4',
    rating: 4.4,
    reviewCount: 75,
    featured: false,
    sizes: ['S', 'M', 'L'],
    images: ['prod-4'],
  },
  {
    id: 'prod-5',
    name: 'Classic Denim Jacket',
    description: 'A timeless denim jacket that never goes out of style. A must-have for any wardrobe.',
    price: 3500,
    category: 'Jackets',
    brand: 'Denim Co.',
    tags: ['jacket', 'denim', 'casual'],
    imageId: 'prod-5',
    rating: 4.9,
    reviewCount: 230,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['prod-5'],
  },
  {
    id: 'prod-6',
    name: 'Comfortable White Sneakers',
    description: 'Versatile and comfortable white sneakers that go with almost any casual outfit.',
    price: 2500,
    category: 'Shoes',
    brand: 'ComfyKicks',
    tags: ['sneakers', 'casual', 'white'],
    imageId: 'prod-6',
    rating: 4.6,
    reviewCount: 180,
    featured: false,
    sizes: ['6', '7', '8', '9', '10'],
    images: ['prod-6'],
  },
  {
    id: 'prod-7',
    name: 'Minimalist Gold Necklace Set',
    description: 'A beautiful set of three minimalist necklaces, plated in gold. Perfect for layering.',
    price: 1500,
    category: 'Accessories',
    brand: 'Golden Layers',
    tags: ['necklace', 'gold', 'jewelry'],
    imageId: 'prod-7',
    rating: 4.7,
    reviewCount: 95,
    featured: false,
    images: ['prod-7'],
  },
  {
    id: 'prod-8',
    name: 'Wide-Brimmed Sun Hat',
    description: 'Stay protected from the sun in style with this fashionable wide-brimmed hat.',
    price: 1200,
    category: 'Accessories',
    brand: 'SunGuard',
    tags: ['hat', 'sun protection', 'beach'],
    imageId: 'prod-8',
    rating: 4.3,
    reviewCount: 60,
    featured: false,
    images: ['prod-8'],
  },
  {
    id: 'prod-9',
    name: 'Tortoise Shell Sunglasses',
    description: 'Chic designer sunglasses with a classic tortoise shell frame. 100% UV protection.',
    price: 2800,
    category: 'Accessories',
    brand: 'ShadeMasters',
    tags: ['sunglasses', 'designer', 'uv protection'],
    imageId: 'prod-9',
    rating: 4.8,
    reviewCount: 110,
    featured: true,
    images: ['prod-9'],
  },
  {
    id: 'prod-10',
    name: 'Cozy Cashmere Sweater',
    description: 'Luxuriously soft and warm cashmere sweater. Perfect for chilly days.',
    price: 7500,
    category: 'Tops',
    brand: 'LuxeWear',
    tags: ['sweater', 'cashmere', 'winter'],
    imageId: 'prod-10',
    rating: 4.9,
    reviewCount: 140,
    featured: false,
    sizes: ['S', 'M', 'L'],
    images: ['prod-10'],
  },
  {
    id: 'prod-11',
    name: 'High-Waisted Tailored Trousers',
    description: 'Elegant high-waisted trousers, tailored for a perfect fit. Ideal for office or formal wear.',
    price: 4200,
    category: 'Trousers',
    brand: 'PowerDresser',
    tags: ['trousers', 'formal', 'office wear'],
    imageId: 'prod-11',
    rating: 4.6,
    reviewCount: 90,
    featured: false,
    sizes: ['28', '30', '32', '34'],
    images: ['prod-11'],
  },
  {
    id: 'prod-12',
    name: 'Paisley Silk Scarf',
    description: 'A beautiful silk scarf with an intricate paisley pattern. Adds a pop of color to any outfit.',
    price: 1900,
    category: 'Accessories',
    brand: 'Silk Route',
    tags: ['scarf', 'silk', 'paisley'],
    imageId: 'prod-12',
    rating: 4.7,
    reviewCount: 80,
    featured: false,
    images: ['prod-12'],
  },
  {
    id: 'prod-13',
    name: 'Push-up Bra & Panty Set',
    description: 'A stunning push-up bra and panty set designed to enhance your natural shape. Made with soft lace and microfiber.',
    price: 2499,
    category: 'Bra & Panty Sets',
    brand: 'Intimates Co.',
    tags: ['lingerie', 'push-up', 'lace'],
    imageId: 'prod-13',
    rating: 4.8,
    reviewCount: 110,
    featured: false,
    sizes: ['32', '34', '36', '38'],
    images: ['prod-13'],
  },
  {
    id: 'prod-14',
    name: 'Lace Bralette & Thong Set',
    description: 'A delicate and comfortable lace bralette paired with a matching thong. Perfect for everyday luxury.',
    price: 1999,
    category: 'Bra & Panty Sets',
    brand: 'Intimates Co.',
    tags: ['lingerie', 'bralette', 'lace'],
    imageId: 'prod-14',
    rating: 4.7,
    reviewCount: 95,
    featured: true,
    sizes: ['32', '34', '36', '38'],
    images: ['prod-14'],
  },
  {
    id: 'prod-15',
    name: 'Bikini Style Bra & Panty',
    description: 'A classic bikini-style bra and panty set in a vibrant color. Offers great comfort and support.',
    price: 1799,
    category: 'Bra & Panty Sets',
    brand: 'BeachBabe',
    tags: ['lingerie', 'bikini', 'swimwear'],
    imageId: 'prod-15',
    rating: 4.6,
    reviewCount: 85,
    featured: false,
    sizes: ['32', '34', '36', '38'],
    images: ['prod-15'],
  },
  {
    id: 'prod-16',
    name: 'Colorful Lace Bralette Set',
    description: 'A set of beautiful and comfortable lace bralettes in various colors. Perfect for a stylish and relaxed look.',
    price: 599,
    category: 'Bra & Panty Sets',
    brand: 'Lace & Co',
    tags: ['bralette', 'lace', 'colorful'],
    imageId: 'prod-16',
    rating: 4.6,
    reviewCount: 78,
    featured: false,
    sizes: ['30', '32', '34', '36', '38', '40', '42'],
    images: ['prod-16'],
  },
  {
    id: 'diwali-1',
    name: 'Embroidered Festive Kurta',
    description: 'A beautifully embroidered kurta, perfect for Diwali celebrations. Made from rich silk fabric.',
    price: 2699,
    originalPrice: 2999,
    category: 'Diwali Collection',
    brand: 'Festive Threads',
    tags: ['diwali', 'kurta', 'ethnic wear', 'sale'],
    imageId: 'diwali-1',
    rating: 4.8,
    reviewCount: 50,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    images: ['diwali-1'],
  },
  {
    id: 'diwali-2',
    name: 'Hand-Painted Diya Set',
    description: 'Set of 12 beautifully hand-painted clay diyas to illuminate your home this Diwali.',
    price: 449,
    originalPrice: 499,
    category: 'Diwali Collection',
    brand: 'Crafts of India',
    tags: ['diwali', 'diya', 'decor', 'sale'],
    imageId: 'diwali-2',
    rating: 4.9,
    reviewCount: 85,
    featured: true,
    images: ['diwali-2'],
  },
  {
    id: 'diwali-3',
    name: 'Designer Silk Saree',
    description: 'An elegant designer saree made from pure silk, featuring intricate zari work. Perfect for festive occasions.',
    price: 8999,
    originalPrice: 9999,
    category: 'Diwali Collection',
    brand: 'Royal Weaves',
    tags: ['diwali', 'saree', 'silk', 'sale'],
    imageId: 'diwali-3',
    rating: 4.7,
    reviewCount: 40,
    featured: false,
    images: ['diwali-3'],
  },
];

export const orders: Order[] = [
  {
    id: 'order-123',
    date: '2023-10-26',
    total: 7499,
    status: 'Shipped',
    items: [
      { id: 'prod-1', name: 'Stylish Blue Dress', price: 2999, quantity: 1, imageId: 'prod-1' },
      { id: 'prod-2', name: 'Elegant High Heels', price: 4500, quantity: 1, imageId: 'prod-2' },
    ],
  },
  {
    id: 'order-456',
    date: '2023-10-20',
    total: 3500,
    status: 'Delivered',
    items: [
      { id: 'prod-5', name: 'Classic Denim Jacket', price: 3500, quantity: 1, imageId: 'prod-5' },
    ],
  },
  {
    id: 'order-789',
    date: '2023-11-01',
    total: 4000,
    status: 'Processing',
    items: [
        { id: 'prod-6', name: 'Comfortable White Sneakers', price: 2500, quantity: 1, imageId: 'prod-6' },
        { id: 'prod-7', name: 'Minimalist Gold Necklace Set', price: 1500, quantity: 1, imageId: 'prod-7' },
    ]
  },
  {
    id: 'order_PUZXoAvmx0KYQ6',
    date: '2024-07-30',
    total: 3449,
    status: 'Processing',
    items: [
        { id: 'prod-1', name: 'Stylish Blue Dress', price: 2999, quantity: 1, imageId: 'prod-1' },
        { id: 'diwali-2', name: 'Hand-Painted Diya Set', price: 449, quantity: 1, imageId: 'diwali-2' },
    ]
  }
];

// Helper functions to query the mock data
export const getProductById = (id: string): Product | undefined => products.find(p => p.id === id);
export const getProductsByIds = (ids: string[]): Product[] => products.filter(p => ids.includes(p.id));
export const getOrderById = (id: string): Order | undefined => orders.find(o => o.id === id);
export const getFeaturedProducts = (): Product[] => products.filter(p => p.featured);

    
